### ISSUE TITLE
Use Ed25519

### ISSUE THREAD

**Issue by fd74a05d0b** [spance/deblocus#15]
Ed25519 is faster and more secure than RSA.
https://github.com/agl/ed25519

**Comment by spance** [comment]
the ed25519 is a implementor of ECDSA just for digital signature, not a ECC(Elliptic curve cryptography), that cannot be used to encrypt and decrypt data.

**Comment by spance** [comment]
and you should not worry about the performance in deblocus rsa encryption, because the rsa only be used to encrypt a little data for handshake, generally, the encrypted data by rsa was less than 117 bytes.
