### ISSUE TITLE
openwrt的可行性

### ISSUE THREAD

**Issue by juyyao** [spance/deblocus#2]
能否编译一个openwrt AR71XX系列的ipk包?想测试下能否在路由里翻~谢谢你的付出~

**Comment by spance** [comment]
Linux-ARM平台肯定是没问题的，但是我附近没有刷openwrt的设备，而且对openwrt平台不是很了解，所以估计短期内还无法满足openwrt平台吧。

**Comment by juyyao** [comment]
我不是学开发的~所以也没能帮上什么忙~等待懂行的开发人员好了~

**Comment by spance** [comment]
如果你是想给局域网用，那完全可以跑在局域网任何一个机器上，难道非要跑在路由器上吗？

**Comment by juyyao** [comment]
现在手持设备比较多啊~先发个安卓apk应该推广起来快点

**Comment by spance** [comment]
嗯，手持设备是在考虑中的，比如就计划实现客户端http proxy那就在移动设备配Http proxy到deblocus客户端上。
此外，还在考虑实现一个web pac管理，比如手机上设置一个pac地址，可以定义多套方案，比如Home Work等等，比如Home方案里面包括一堆地址走向deblocus home network，比如Work方案里面走向公司某地址的deblocus等等，一个书签做切换就够了完全可以不用客户端（尤其像对环境有洁癖的），那对iOS android都会很方便，而且也可以考虑把PC Chrome的代理切换也加入进去，我觉得这是一个既节省客户机资源空间，也很方便的方式。

**Comment by juyyao** [comment]
想法挺好~但是很容易被商业化,还是先把基础做好了,毕竟功能还是为了穿越~推开来才可以做测试和改进~加油吧~爱莫能助了我~
