### ISSUE TITLE
无法生成d5c文件

### ISSUE THREAD

**Issue by babykidp** [spance/deblocus#9]
服务器端执行这一步时：
```$./deblocus -icc <SERVER_PUBLIC_ADDRESS> <USER1> ```
发生错误：
```missing port in address <SERVER_PUBLIC_ADDRESS>```
原先设置了iptables规则，执行上述步骤时发生错误；清除了iptables规则，还是发生错误。
请问是端口设置有问题吗？还是有其他原因？谢谢！

**Comment by spance** [comment]
请用./deblocus -icc 1.2.3.4:7788 user1
-icc后面第一个参数是ip:port，再后面才是用户名可以多个

**Comment by babykidp** [comment]
多谢帮助，已配置成功，可正常使用。
